name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dex-k8s-authenticator:$(date +%s)
    - name: Docker Hub login
      env:
        DOCKER_HUB_USER: ${{secrets.DOCKER_HUB_USER}}
        DOCKER_HUB_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
      run: |
        docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - name: Docker Hub push image
      run: |
        docker push ${{secrets.DOCKER_HUB_USER}}/dex-k8s-authenticator
